name: Build bottles

on:
  push:
    branches:
      - "bump-*"
    paths:
      - "Formula/**.rb"
  workflow_dispatch:
    inputs:
      formula:
        description: Formula to build the bottle for
        required: true

permissions:
  contents: write

jobs:
  prep:
    runs-on: macos-latest
    outputs:
      formula: ${{ steps.get-info.outputs.formula }}
      version: ${{ steps.get-info.outputs.version }}
      root_url: ${{ steps.get-info.outputs.root_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: get-info
        env:
          REPO: ${{ github.repository }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          if [ -n "${{ github.event.inputs.formula }}" ]; then
            FORMULA="${{ github.event.inputs.formula }}"
            FORMULA_FILE="Formula/$FORMULA.rb"
          else
            FORMULA_FILE=$(git diff --name-only origin/main...HEAD | grep "Formula/.*\\.rb" | head -n1)
            FORMULA=$(basename "$FORMULA_FILE" .rb)
          fi

          brew tap "${REPO}"
          VERSION=$(brew info --json --formula "$FORMULA" | jq -r '.[0].versions.stable')
          ROOT_URL="https://github.com/$REPO/releases/download/$FORMULA-v$VERSION"
          {
            echo "formula=$FORMULA"
            echo "version=$VERSION"
            echo "root_url=$ROOT_URL"
          } >> "$GITHUB_OUTPUT"

  test-bot:
    needs: prep
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@main

      - name: Build and upload bottle
        id: build
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORMULA: ${{ needs.prep.outputs.formula }}
          ROOT_URL: ${{ needs.prep.outputs.root_url }}
        run: |
          set -euo pipefail

          brew test-bot "$FORMULA"
          brew bottle --json --root-url="$ROOT_URL" "$FORMULA"

          TARBALL=$(ls -- *.bottle*.tar.gz)
          JSON_FILE=$(ls -- *.bottle.json)
          BOTTLE=$(jq -r '.. | .filename? | select(.)' "$JSON_FILE" | head -n 1)
          mv "$TARBALL" "$BOTTLE"

      - name: Upload bottle and JSON
        uses: actions/upload-artifact@v4
        with:
          name: bottles-${{ matrix.os }}
          path: |
            *.bottle*.tar.gz
            *.bottle.json

  release:
    needs: [prep, test-bot]
    if: success() || failure()
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@main

      - name: Download all bottle artifacts
        uses: actions/download-artifact@v4
        with:
          path: bottles
          pattern: bottles-*
          merge-multiple: true

      - name: Release
        id: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROOT_URL: ${{ needs.prep.outputs.root_url }}
          FORMULA: ${{ needs.prep.outputs.formula }}
          VERSION: ${{ needs.prep.outputs.version }}
        run: |
          set -euo pipefail

          if [ -z "$(ls bottles/*.tar.gz 2>/dev/null)" ]; then
            echo "No bottles were built, exiting."
            exit 0
          fi

          TAG="$FORMULA-v$VERSION"
          if ! gh release view "$TAG" &>/dev/null; then
            gh release create "$TAG" --title "$FORMULA v$VERSION"
          fi
          gh release upload "$TAG" bottles/*.tar.gz --clobber

          brew bottle --merge --write --no-commit --root-url="$ROOT_URL" bottles/*.bottle.json

          echo commit=1 >> "$GITHUB_OUTPUT"

      - name: Commit changes
        if: steps.release.outputs.commit == '1'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "${{ needs.prep.outputs.formula }} ${{ needs.prep.outputs.version }} bottle block [skip ci]"
          file_pattern: "Formula/${{ needs.prep.outputs.formula }}.rb"
