name: Build bottles

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "Formula/**.rb"

permissions:
  contents: write

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      formula-file: ${{ steps.get-info.outputs.formula-file }}
      formula: ${{ steps.get-info.outputs.formula }}
      version: ${{ steps.get-info.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: get-info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          FILE=$(gh pr view ${{ github.event.pull_request.number }} --json files -q '.files[0].path')
          FORMULA=$(basename "$FILE" .rb)
          VERSION=$(echo "$PR_TITLE" | awk '{print $2}')

          echo "formula-file=$FILE" >> $GITHUB_OUTPUT
          echo "formula=$FORMULA" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  test-bot:
    needs: prep
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@main

      - name: Build and upload bottle
        id: build
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORMULA: ${{ needs.prep.outputs.formula }}
          VERSION: ${{ needs.prep.outputs.version }}
        run: |
          set -euo pipefail

          brew test-bot "$FORMULA"
          brew bottle --json --root-url="https://github.com/${{ github.repository }}/releases/download/$FORMULA-v$VERSION" "$FORMULA"

          TARBALL=$(ls *.bottle*.tar.gz)
          JSON_FILE=$(ls *.bottle.json)
          BOTTLE=$(jq -r '.. | .filename? | select(.)' "$JSON_FILE" | head -n 1)
          mv "$TARBALL" "$BOTTLE"

      - name: Upload bottle and JSON
        uses: actions/upload-artifact@v4
        with:
          name: bottles-${{ matrix.os }}
          path: |
            *.bottle*.tar.gz
            *.bottle.json

  release:
    needs: [prep, test-bot]
    if: success() || failure()
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@main

      - name: Download all bottle artifacts
        uses: actions/download-artifact@v4
        with:
          path: bottles
          pattern: bottles-*
          merge-multiple: true

      - name: Release
        id: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORMULA: ${{ needs.prep.outputs.formula }}
          VERSION: ${{ needs.prep.outputs.version }}
        run: |
          set -euo pipefail

          if [ -z "$(ls bottles/*.tar.gz 2>/dev/null)" ]; then
            echo "No bottles were built, exiting."
            exit 0
          fi

          if ! gh release view "$FORMULA-v$VERSION" &>/dev/null; then
            gh release create "$FORMULA-v$VERSION" --title "$FORMULA v$VERSION"
          fi
          gh release upload "$FORMULA-v$VERSION" bottles/*.tar.gz --clobber

          echo "tag=$FORMULA-v$VERSION" >> $GITHUB_OUTPUT

      - name: Update formula file
        if: steps.release.outputs.tag != ''
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORMULA_FILE: ${{ needs.prep.outputs.formula-file }}
        run: |
          set -euo pipefail

          brew bottle --merge --write --no-commit --root-url="https://github.com/${{ github.repository }}/releases/download/${{ steps.release.outputs.tag }}" bottles/*.bottle.json

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$FORMULA_FILE"
          git commit -m "Update bottles for $FORMULA_FILE [skip ci]" || echo "No changes to commit"
          git push origin HEAD
