name: Test CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@main

      - name: Run sshx
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sSf https://sshx.io/get | sh -s run
