name: Update rime-ls

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  FORMULA: rime-ls
  UPSTREAM: wlh320/rime-ls

permissions:
  contents: write

jobs:
  check:
    runs-on: macos-latest
    outputs:
      version: ${{ steps.livecheck.outputs.version }}
      url: ${{ steps.livecheck.outputs.url }}
      sha256: ${{ steps.livecheck.outputs.sha256 }}
    steps:
      - id: livecheck
        env:
          EVENT: ${{ github.event_name }}
          REPO: ${{ github.repository }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          brew tap $REPO

          brew livecheck $REPO/$FORMULA --json > livecheck.json
          PROCEED=$(jq -r '.[0].version.outdated' livecheck.json)

          if [ "$EVENT" = "workflow_dispatch" ]; then
            PROCEED="true"
          fi

          if [ "$PROCEED" = "true" ]; then
            VERSION=$(jq -r '.[0].version.latest' livecheck.json)
            echo "version=$VERSION" >> $GITHUB_OUTPUT

            BASE_URL="https://github.com/$UPSTREAM/archive/refs/tags"
            TAG=$(gh release list --repo $UPSTREAM --json tagName --jq '.[0].tagName')
            NEW_URL="$BASE_URL/$TAG.tar.gz"
            echo "url=$NEW_URL" >> $GITHUB_OUTPUT

            SHA256=$(curl -L $NEW_URL | shasum -a 256 | awk '{print $1}')
            echo "sha256=$SHA256" >> $GITHUB_OUTPUT

            if ! gh release view "$FORMULA-v$VERSION" &>/dev/null; then
              gh release create "$FORMULA-v$VERSION" --title "$FORMULA v$VERSION"
            fi
          else
            echo "version=" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check
    if: needs.check.outputs.version != ''
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@main

      - name: Build bottle
        env:
          NEW_URL: ${{ needs.check.outputs.url }}
          NEW_SHA: ${{ needs.check.outputs.sha256 }}
          VERSION: ${{ needs.check.outputs.version }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          sed -i.bak "s|url \".*\"|url \"$NEW_URL\"|" Formula/$FORMULA.rb
          sed -i.bak "s/sha256 \".*\"/sha256 \"$NEW_SHA\"/" Formula/$FORMULA.rb

          brew install --build-bottle "${{ github.repository }}/$FORMULA"
          brew bottle --json --root-url="https://github.com/${{ github.repository }}/releases/download/$FORMULA-v$VERSION" "$FORMULA"

          BOTTLE_FILE=$(ls *.bottle*.tar.gz)
          JSON_FILE=$(ls *.bottle.json)
          FILENAME=$(jq -r '.[].bottle.tags.[].filename' "$JSON_FILE")
          mv "$BOTTLE_FILE" "$FILENAME"
          gh release upload "$FORMULA-v$VERSION" "$FILENAME" --clobber

      - name: Upload bottle and JSON
        uses: actions/upload-artifact@v4
        with:
          name: bottles-${{ matrix.os }}
          path: |
            *.bottle.json
          if-no-files-found: error

  release:
    needs: [check, build]
    if: needs.check.outputs.version != ''
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@main

      - name: Download all bottle artifacts
        uses: actions/download-artifact@v4
        with:
          path: bottles
          pattern: bottles-*
          merge-multiple: true

      - name: Update formula file
        env:
          VERSION: ${{ needs.check.outputs.version }}
          NEW_URL: ${{ needs.check.outputs.url }}
          NEW_SHA: ${{ needs.check.outputs.sha256 }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          sed -i.bak "s|url \".*\"|url \"$NEW_URL\"|" Formula/$FORMULA.rb
          sed -i.bak "s/sha256 \".*\"/sha256 \"$NEW_SHA\"/" Formula/$FORMULA.rb

          brew bottle --merge --write --no-commit bottles/*.bottle.json --root-url="https://github.com/${{ github.repository }}/releases/download/$FORMULA-v$VERSION"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "${{ env.FORMULA }} ${{ needs.check.outputs.version }}"
          title: "Bump ${{ env.FORMULA }} to v${{ needs.check.outputs.version }}"
          body: "Automated update for ${{ env.FORMULA }} version v${{ needs.check.outputs.version }}"
          base: main
          branch: "update/${{ env.FORMULA }}-v${{ needs.check.outputs.version }}"
          delete-branch: true
          add-paths: "Formula/${{ env.FORMULA }}.rb"
