name: Update propertree

on:
  schedule:
    # Runs weekly on Sunday at midnight UTC
    - cron: "0 0 * * 0"
  workflow_dispatch:

env:
  FORMULA: propertree
  UPSTREAM: corpnewt/ProperTree

permissions:
  contents: write
  pull-requests: write

jobs:
  update-formula-pr:
    runs-on: macos-latest
    steps:
      - name: Check for updates using brew livecheck
        id: livecheck
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          brew tap "${{ github.repository }}"
          brew livecheck --json $FORMULA > livecheck.json
          outdated=$(jq -r '.[0].version.outdated' livecheck.json)
          if [ "$outdated" = "true" ]; then
            version=$(jq -r '.[0].version.latest' livecheck.json)
            echo "version=$version" >> $GITHUB_OUTPUT
            commit=$(gh api repos/$UPSTREAM/commits --jq '.[0].sha')
            echo "commit=$commit" >> $GITHUB_OUTPUT
          else
            echo "version=" >> $GITHUB_OUTPUT
          fi

      - name: Update Homebrew formula
        if: steps.livecheck.outputs.version != ''
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          version="${{ steps.livecheck.outputs.version }}"
          commit="${{ steps.livecheck.outputs.commit }}"
          url="https://github.com/$UPSTREAM/archive/${commit}.tar.gz"

          brew bump-formula-pr \
            --no-audit \
            --no-fork \
            --url "$url" \
            --version "$version" \
            ${{ github.repository }}/$FORMULA
