name: Update battery

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-formula-pr:
    runs-on: macos-latest
    steps:
      - name: Get current formula version
        id: livecheck
        run: |
          set -euo pipefail
          brew tap "${{ github.repository }}"
          brew livecheck --json battery > livecheck.json
          outdated=$(jq -r '.[0].version.outdated' livecheck.json)
          if [ "$outdated" = "true" ]; then
            version=$(jq -r '.[0].version.latest' livecheck.json)
            echo "version=$version" >> $GITHUB_OUTPUT
          else
            echo "version=" >> $GITHUB_OUTPUT
          fi

      - name: Create Formula Update PR
        if: steps.livecheck.outputs.version != ''
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          brew bump-formula-pr \
            --no-audit \
            --no-fork \
            --version="${{ steps.livecheck.outputs.version }}" \
            "${{ github.repository }}/battery"
